#!/usr/bin/env python

import logging
import sys

from githooks.cmd import Hooks

logging.basicConfig(
    stream=sys.stdout,
    level=logging.INFO,
    format='%(message)s',
)

sys.exit(Hooks().run())
