#!/usr/bin/env python
import sys

from githooks import runners, repo

print('woot hook')
print('Added files:', repo.added_files())
print('Modified files:', repo.modified_files())
print('Deleted files:', repo.deleted_files())

sys.exit(1)

if __name__ == '__main__':
    sys.exit(runners.PreCommitHookRunner().run())
